spring:
  redis:
    host: localhost
    port: 6379
zuul:
  sensitive-headers: 
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
  ignored-patterns:
    - /**/product/listForOrder
